[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED @ ^3.5.0
    earlephilhower/ESP8266Audio @ ^1.9.9
    claw/BH1750 @ ^1.0.0
    arduino-libraries/SD @ ^1.2.4
    espressif/WiFi @ ^1.0
    RemoteXY/RemoteXY @ ^1.4.1
